version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/" # root of the repo with go.work
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 5
