root = "."
tmp_dir = ".bin"

[build]
  bin = "./.bin/${SERVICE_NAME}"
  cmd = "make build-one SERVICE=${SERVICE_NAME}"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"
  kill_delay = "0s"
  rerun_delay = 500
  stop_on_error = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
