services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"   # Jaeger UI
      - "4318:4318"     # OTLP HTTP (what your app uses)
    environment:
      - COLLECTOR_OTLP_ENABLED=true

