services:
  aura:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: aura
    ports:
      - "8080:8080"
    networks:
      - aura-net


networks:
  aura-net:
    driver: bridge
